const actionTypes = {
    ADD_LOCATION: "ADD_LOCATION",
    ADD_START_DATE: "ADD_START_DATE",
    ADD_END_DATE: "ADD_END_DATE",
    ADD_ADULTS: "ADD_ADULTS",
    ADD_CHILDREN: "ADD_CHILDREN",
    ADD_INFANTS: "ADD_INFANTS",
    ADD_PETS: "ADD_PETS",
    SHOW_PRICE_CHART: "SHOW_PRICE_CHART",
    ADD_LAT: "ADD_LAT",
    ADD_LANG: "ADD_LANG",
};

export default actionTypes;