const actionTypes = {
    ADD_LOCATION: "ADD_LOCATION",
    ADD_START_DATE: "ADD_START_DATE",
    ADD_END_DATE: "ADD_END_DATE",
    ADD_ADULTS: "ADD_ADULTS",
    ADD_CHILDREN: "ADD_CHILDREN",
    ADD_INFANTS: "ADD_INFANTS",
    ADD_PETS: "ADD_PETS",
};

export default actionTypes;